name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # MUITO IMPORTANTE: Verifique se 'main' é a branch principal do seu repositório. Se for 'master', mude aqui.
  workflow_dispatch: # Permite que você acione o workflow manualmente pela interface do GitHub

jobs:
  build:
    runs-on: ubuntu-latest # O sistema operacional onde o build será executado no GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Baixa o código do seu repositório

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1 # Configura o ambiente Ruby necessário
      with:
        ruby-version: '3.2' # Tenta Ruby 3.2 para melhor compatibilidade. Pode tentar '3.1' novamente se 3.2 falhar.
        # Removemos bundler-cache: true para forçar a instalação do Bundler e gems do zero.

    - name: Install Bundler specific version
      run: |
        gem install bundler:2.5.9 # Instala uma versão específica do Bundler. '2.5.9' é uma versão estável recente.
        bundle _2.5.9 install --jobs 4 --retry 3 # Usa a versão instalada para instalar as gems.

    - name: Add platform to bundler lockfile
      run: bundle lock --add-platform x86_64-linux # Continua sendo necessário para lidar com a diferença de plataformas.

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --trace # Roda o build do Jekyll. --trace para mais detalhes em caso de erro.
      env: # Define variáveis de ambiente para o build, se necessário.
        JEKYLL_ENV: production # Define o ambiente para produção.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # Ação que faz o deploy para o GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token fornecido pelo GitHub automaticamente.
        publish_dir: ./_site # A pasta onde o Jekyll gera o site HTML.